export const SliderData = [
    {
      image:
        'https://i.ibb.co/484wdNb/env1.png'
    },    
    {
      image:
        'https://i.ibb.co/YLp4WjX/env2.png'
    },
    {
      image:
        'https://i.ibb.co/Ht8DVRH/env3.png'
    },
    {
      image:
        'https://i.ibb.co/yNn3gyM/env4.png'
    },
    {
      image:
        'https://i.ibb.co/yNn3gyM/env4.png'
    }
];